CREATE DATABASE IF NOT EXISTS Venta_de_entradas;
USE Venta_de_entradas;

CREATE TABLE ESPECTACULOS (
    COD_ESPECTACULO VARCHAR(50) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    FECHA_INICIAL DATE NOT NULL,
    FECHA_FINAL DATE NOT NULL,
    INTERPRETE VARCHAR(100) NOT NULL,
    COD_RECINTO VARCHAR(50) NOT NULL,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO)
);

CREATE TABLE PRECIOS_ESPECTACULOS (
    COD_ESPECTACULO VARCHAR(50),
    COD_RECINTO VARCHAR(50),
    ZONA VARCHAR (100),
    PRECIO INT UNSIGNED CHECK (PRECIO>0),
    PRIMARY KEY (COD_ESPECTACULO, COD_RECINTO, ZONA),
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO),
    FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA)
);

CREATE TABLE RECINTOS (
    COD_RECINTO VARCHAR(50) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    HORARIO VARCHAR(200) NOT NULL
);

CREATE TABLE ZONAS_RECINTOS (
    COD_RECINTO VARCHAR (50),
    ZONA VARCHAR (100),
    CAPACIDAD INT UNSIGNED CHECK (CAPACIDAD>0) NOT NULL,
    PRIMARY KEY (COD_RECINTO, ZONA),
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO)
);

CREATE TABLE ASIENTOS (
    COD_RECINTO VARCHAR (50),
    ZONA VARCHAR (100),
    FILA INT UNSIGNED,
    NUMERO INT UNSIGNED,
    PRIMARY KEY (COD_RECINTO, ZONA, FILA, NUMERO),
    FOREIGN KEY (COD_RECINTO, ZONA) REFERENCES ZONAS_RECINTOS(COD_RECINTO, ZONA)
);

CREATE TABLE REPRESENTACIONES (
    COD_ESPECTACULO VARCHAR (50),
    FECHA DATE,
    HORA TIME,
    PRIMARY KEY (COD_ESPECTACULO, FECHA, HORA),
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO)
);

CREATE TABLE ENTRADAS (
    COD_ESPECTACULO VARCHAR (50),
    FECHA DATE,
    HORA TIME,
    COD_RECINTO VARCHAR (50),
    FILA INT,
    NUMERO INT,
    ZONA VARCHAR (100) NOT NULL,
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    PRIMARY KEY (COD_ESPECTACULO, FECHA, HORA, COD_RECINTO, FILA, NUMERO),
    FOREIGN KEY (COD_ESPECTACULO, FECHA, HORA) REFERENCES REPRESENTACIONES(COD_ESPECTACULO, FECHA, HORA),
    FOREIGN KEY (COD_RECINTO, FILA, NUMERO, ZONA) REFERENCES ASIENTOS(COD_RECINTO, FILA, NUMERO, ZONA),
    FOREIGN KEY (DNI_CLIENTE) REFERENCES ESPECTADORES(DNI_CLIENTE)
);

CREATE TABLE ESPECTADORES (
    DNI_CLIENTE VARCHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR (100) NOT NULL,
    DIRECCION  VARCHAR (100) NOT NULL,
    TELEFONO  VARCHAR (20) NOT NULL,
    CIUDAD  VARCHAR (100) NOT NULL,
    NTARJETA  VARCHAR (16) NOT NULL
);
